<tr>
			
	<td height="50px" width="200px" class="clsMenu clsNegrito clsCentro clsMeio">	
		
		<a href="#" onclick="fnValidarDados('incluir');">
		Incluir
		</a>
		
	</td>
	
	<td height="50px" width="200px" class="clsMenu clsNegrito clsCentro clsMeio">	
		<a href="#" onclick="fnValidarDados('alterar');">
		Alterar
		</a>
	</td>
	
	<td height="50px" width="200px" class="clsMenu clsNegrito clsCentro clsMeio">	
		<a href="#" onclick="fnValidarDados('consultar');">
		Consultar
		</a>
	</td>
	
	<td height="50px" width="200px" class="clsMenu clsNegrito clsCentro clsMeio">	
		<a href="#" onclick="fnValidarDados('excluir');">
		Excluir
		</a>
	</td>
	
	<td height="50px" width="200px" class="clsMenu clsNegrito clsCentro clsMeio">	
		<a href="#" onclick="fnValidarDados('limpar');">
		Limpar		
		</a>
	</td>
	
</tr>